table Dim_territory
	excludeFromModelRefresh
	lineageTag: dde0ce13-9580-4083-be61-758b900bcc0e

	column SalesTerritoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 6d55b280-1936-4c83-a5d0-03ddc97d7165
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 8474064f-6b0b-44e9-9bc5-594f9eda3d81
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 3e1424d0-f0e3-4fca-b45f-c508596d136a
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: string
		lineageTag: 4f00b6b5-e83f-48c7-a094-52d35729007c
		dataCategory: Continent
		summarizeBy: none
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

	partition Dim_territory = m
		mode: import
		source =
				let
				    Source = MySQL.Database(ServerName, DataBaseName, [ReturnSingleDatabase=true]),
				    bikevista_dev_territory = Source{[Schema=DataBaseName,Item="territory"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(bikevista_dev_territory,{DataBaseName & ".returns_data", DataBaseName & ".sales_data"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

