table product_categories
	excludeFromModelRefresh
	lineageTag: b558ad3d-0703-49b0-80a2-afb4bdf2f8dd

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 0ecc1f79-a0e2-4282-8b9a-24db1e2910a2
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductCategoryName
		dataType: string
		lineageTag: d6be5235-1254-458a-bc52-5b5aaa55094b
		summarizeBy: none
		sourceColumn: ProductCategoryName

		annotation SummarizationSetBy = Automatic

	partition product_categories = m
		mode: import
		source =
				let
				    Source = MySQL.Database(ServerName, DataBaseName, [ReturnSingleDatabase=true]),
				    bikevista_dev_product_categories = Source{[Schema=DataBaseName,Item="product_categories"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(bikevista_dev_product_categories, {DataBaseName & ".product_subcategories"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

