table product_subcategories
	excludeFromModelRefresh
	lineageTag: 5dac0bfd-d85c-4006-83ca-bf6134da5c9b

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 7cf268f8-a8b2-407b-9451-016418b99054
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryName
		dataType: string
		lineageTag: 6b2dbf14-b4dc-424f-89dc-3caed2140e53
		summarizeBy: none
		sourceColumn: ProductSubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 16a3e17c-5930-46a4-bcbd-1b9cfccca5da
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition product_subcategories = m
		mode: import
		source =
				let
				    Source = MySQL.Database(ServerName, DataBaseName, [ReturnSingleDatabase=true]),
				    bikevista_dev_product_subcategories = Source{[Schema=DataBaseName ,Item="product_subcategories"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(bikevista_dev_product_subcategories,{DataBaseName & ".product", DataBaseName & ".product_categories"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

